export const type = {
    // Sync
    FILL_TASKS:          'FILL_TASKS',
    CREATE_TASK:         'CREATE_TASK',
    NEW_TASK:            'NEW_TASK',
    CANCEL_NEW_TASK:     'CANCEL_NEW_TASK',
    REMOVE_TASK:         'REMOVE_TASK',
    COMPLETE_TASK:       'COMPLETE_TASK',
    START_RUN_TASK:      'START_RUN_TASK',
    END_RUN_TASK:        'END_RUN_TASK',
    CHANGE_TASK:         'CHANGE_TASK',
    MAKE_ORDER_LIST:     'MAKE_ORDER_LIST',
    NEW_ORDER_LIST:      'NEW_ORDER_LIST',
    // Asynс
    FETCH_TASKS_ASYNC:   'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC:   'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC:   'REMOVE_TASK_ASYNC',
    COMPLETE_TASK_ASYNC: 'COMPLETE_TASK_ASYNC',
    CHANGE_TASK_ASYNC:   'CHANGE_TASK_ASYNC',
};
